### ISSUE TITLE
Red box-colour leaks over toolbar

### ISSUE THREAD

**Issue by ingomohr** [AObuchow/Eclipse-Modern-Dark-Theme#36]
<img width="352" alt="Screenshot 2020-06-11 at 23 48 34" src="https://user-images.githubusercontent.com/2838592/84443456-edc13200-ac3f-11ea-95b1-892a0ea6d544.png">

As discussed w/ @AObuchow, we want to have this fixed. :)

**Comment by AObuchow** [comment]
https://github.com/AObuchow/Eclipse-Modern-Dark-Theme/pull/43/ partly fixes this, although when a part is resized the issue appears again.

**Comment by AObuchow** [comment]
> #43 partly fixes this, although when a part is resized the issue appears again.

I now think that there's an upstream bug that occurs when a view is resized. Will have to make a gif to demonstrate it and file an upstream bug.

**Comment by AObuchow** [comment]
To describe the issue (before getting a gif of it):
When a view that contains a toolbar is resized, all views are also resized (since they all share the common space). It's possible to define a color to use when this resize occurs, however I haven't found a way to define a color to use when resizing **and** when the view is active. 

This issue isn't apparent in the platform dark theme since the tab background colors aren't changed depending on whether they are active or not. This isn't the case for Modern Dark as active tabs get an accent color.

**Comment by AObuchow** [comment]
Here's a gif of the current bug that exists with the toolbar colors. The project explorer toolbar icons background changes to grey upon resizing a view.
![bug](https://media.giphy.com/media/LkfbxEueUVq2LxBRSH/giphy.gif)
(Excuse the low quality gif... I don't know why Giphy made it so small)

This grey coloring (on resize) is coming from [here](https://github.com/AObuchow/Eclipse-Modern-Dark-Theme/blob/master/com.aobuchow.themes.moderndark/css/tabstyle.css#L68).

In theory, this might be fixable by adding something like:

```CSS
.MPartStack.active > CTabFolder > Composite#ToolbarComposite {
  background-color: '#org-eclipse-ui-workbench-PRIMARY_COLOR'; 
}
```

As we want to make the toolbar use the primary color if it's the active view.
However, I'm either not using Eclipse CSS correctly (most likely..) or this requires a fix upstream.

@pyvesb you might have better luck trying to fix this, as you know more about Eclipse CSS than I do :)

**Comment by PyvesB** [comment]
Maybe something like this instead?
```
.MPartStack.active > Composite#ToolbarComposite {
  background-color: '#org-eclipse-ui-workbench-PRIMARY_COLOR'; 
}
```

**Comment by AObuchow** [comment]
@PyvesB yup that worked :D Thank you!!!

**Comment by ingomohr** [comment]
Much better now. Thank you! :) @AObuchow @PyvesB
